set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports e]
set_property IOSTANDARD LVCMOS33 [get_ports postition_rst]
set_property IOSTANDARD LVCMOS33 [get_ports rs]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rw]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports topbottom]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property PACKAGE_PIN B6 [get_ports clk]
set_property PACKAGE_PIN K6 [get_ports postition_rst]
set_property PACKAGE_PIN Y1 [get_ports rst]
set_property PACKAGE_PIN K4 [get_ports topbottom]
set_property PACKAGE_PIN D6 [get_ports rw]
set_property PACKAGE_PIN G6 [get_ports rs]
set_property PACKAGE_PIN A6 [get_ports e]
set_property PACKAGE_PIN D4 [get_ports {data[3]}]
set_property PACKAGE_PIN C3 [get_ports {data[2]}]
set_property PACKAGE_PIN B2 [get_ports {data[1]}]
set_property PACKAGE_PIN A4 [get_ports {data[0]}]


#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets postition_rst_IBUF]


set_property IOSTANDARD LVCMOS33 [get_ports pin_name1]
set_property PACKAGE_PIN L4 [get_ports pin_name1]

set_property IOSTANDARD LVCMOS33 [get_ports init_end]
set_property PACKAGE_PIN M4 [get_ports init_end]

set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property PACKAGE_PIN A2 [get_ports {data[4]}]
set_property PACKAGE_PIN C5 [get_ports {data[5]}]
set_property PACKAGE_PIN C1 [get_ports {data[6]}]
set_property PACKAGE_PIN D1 [get_ports {data[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports print_e]
set_property PACKAGE_PIN N5 [get_ports print_e]

set_property IOSTANDARD LVCMOS33 [get_ports next]
set_property PACKAGE_PIN M1 [get_ports next]

set_property IOSTANDARD LVCMOS33 [get_ports hit_LED]
set_property IOSTANDARD LVCMOS33 [get_ports random]
set_property PACKAGE_PIN M3 [get_ports random]
set_property PACKAGE_PIN M7 [get_ports hit_LED]

set_property IOSTANDARD LVCMOS33 [get_ports die]
set_property IOSTANDARD LVCMOS33 [get_ports life0]
set_property IOSTANDARD LVCMOS33 [get_ports life1]
set_property IOSTANDARD LVCMOS33 [get_ports life2]
set_property IOSTANDARD LVCMOS33 [get_ports {com[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {com[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {com[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {com[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {com[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {com[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {com[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {com[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segdata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segdata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segdata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segdata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segdata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segdata[0]}]
set_property PACKAGE_PIN K5 [get_ports {com[0]}]
set_property PACKAGE_PIN K3 [get_ports {com[1]}]
set_property PACKAGE_PIN K1 [get_ports {com[2]}]
set_property PACKAGE_PIN L6 [get_ports {com[3]}]
set_property PACKAGE_PIN F1 [get_ports {segdata[6]}]
set_property PACKAGE_PIN F5 [get_ports {segdata[5]}]
set_property PACKAGE_PIN E2 [get_ports {segdata[4]}]
set_property PACKAGE_PIN E4 [get_ports {segdata[3]}]
set_property PACKAGE_PIN J1 [get_ports {segdata[2]}]
set_property PACKAGE_PIN J3 [get_ports {segdata[1]}]
set_property PACKAGE_PIN J7 [get_ports {segdata[0]}]
set_property PACKAGE_PIN N5 [get_ports life0]
set_property PACKAGE_PIN M1 [get_ports life1]
set_property PACKAGE_PIN M3 [get_ports life2]
set_property PACKAGE_PIN L4 [get_ports die]

set_property IOSTANDARD LVCMOS33 [get_ports piezo]
set_property PACKAGE_PIN Y21 [get_ports piezo]

set_property PACKAGE_PIN G3 [get_ports {com[4]}]
set_property PACKAGE_PIN G1 [get_ports {com[5]}]
set_property PACKAGE_PIN H6 [get_ports {com[6]}]
set_property PACKAGE_PIN H4 [get_ports {com[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports motorA]
set_property IOSTANDARD LVCMOS33 [get_ports motorB]
set_property IOSTANDARD LVCMOS33 [get_ports motorC]
set_property IOSTANDARD LVCMOS33 [get_ports motorD]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_R[0]}]
set_property PACKAGE_PIN Y20 [get_ports motorA]
set_property PACKAGE_PIN Y22 [get_ports motorB]
set_property PACKAGE_PIN AA20 [get_ports motorC]
set_property PACKAGE_PIN AA21 [get_ports motorD]
set_property PACKAGE_PIN U3 [get_ports {LED_B[3]}]
set_property PACKAGE_PIN W2 [get_ports {LED_B[2]}]
set_property PACKAGE_PIN R5 [get_ports {LED_B[1]}]
set_property PACKAGE_PIN T3 [get_ports {LED_B[0]}]
set_property PACKAGE_PIN U5 [get_ports {LED_G[3]}]
set_property PACKAGE_PIN V1 [get_ports {LED_G[2]}]
set_property PACKAGE_PIN R7 [get_ports {LED_G[1]}]
set_property PACKAGE_PIN T6 [get_ports {LED_G[0]}]
set_property PACKAGE_PIN T2 [get_ports {LED_R[3]}]
set_property PACKAGE_PIN U1 [get_ports {LED_R[2]}]
set_property PACKAGE_PIN P2 [get_ports {LED_R[1]}]
set_property PACKAGE_PIN R3 [get_ports {LED_R[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports startBTN]
set_property PACKAGE_PIN L7 [get_ports startBTN]
